### ISSUE TITLE
The Target/Main Sub needs to be interchanged

### ISSUE THREAD

**Issue by redditindiaspeaks** [impshum/Reddit-Pinned-Sniper#1]
There were issues which had to be fixed, 

1. there is a quit() method on line 62 - this had to removed
2.  open conf.ini ->test_mode = off , maybe should be included in ReadMe

3. main_subreddit = 
target_subreddits =
Where not clear, I had the name of the sub where I want to cross post to target_subreddits, but it was actually the other way around

**Comment by impshum** [comment]
1. Done (my bad).
2. It's already in the readme.
3. It can target multiple subreddits (hence the name).
